name: CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency:
  group: \${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "store = /home/runner/nix"

      - name: Mount cache
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/nix
          key: key

      - name: fake step
        run:  |
          echo path $NIX_PATH
          echo store $NIX_STORE

      - name: fake step 2
        run:  |
          export NIX_STORE=/home/runner/nix/store
          nix-shell --run "echo test"
        shell: bash

      - name: run unit tests
        run:  nix-shell --run "gradle test"

      - name: assemble debug
        run:  nix-shell --run "gradle assembleDebug"

      - name: Calculate version number
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver
          increment: minor

      - name: Create Git tag
        if: github.ref == 'refs/heads/main'
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}

      - name: Create Github Release with debug artifacts
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: ./app/build/outputs/apk/debug/app-debug.apk
