name: CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Grant permissions to nix folder
        run: |
          sudo mkdir -p /nix/store
          sudo chmod -R 777 /nix

      - name: Cache nix
        uses: actions/cache@v3
        with:
         path: |
          # See https://github.com/actions/cache/pull/726
          /nix/store/**
          # Missing something?
          /nix/var/nix/*/*
          /nix/var/nix/db/*
          /nix/var/nix/db/*/**
          !/nix/var/nix/daemon-socket/socket
          !/nix/var/nix/userpool/*
          !/nix/var/nix/gc.lock
          !/nix/var/nix/db/big-lock
          !/nix/var/nix/db/reserved
          /home/runner/.gradle/caches/**
         key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-nix-and-gradle-store

      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check cache hits
        shell: bash
        run: |
          echo "Cache hit: ${{steps.get-cache.outputs.cache-hit}}"

      - name: run unit tests and build
        run:  nix-shell --pure --run "gradle --console=plain --no-daemon testDebug assembleDebug"

      - name: Calculate version number
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver
          increment: minor

      - name: Create Git tag
        if: github.ref == 'refs/heads/main'
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}

      - name: Create Github Release with debug artifacts
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: ./app/build/outputs/apk/debug/app-debug.apk
